// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61lowyAhUQ7QTAIIBV9dStMB08fOfqb0',
    appId: '1:465367019073:web:b072dc23239a6e3a23a0c0',
    messagingSenderId: '465367019073',
    projectId: 'act12-c39ff',
    authDomain: 'act12-c39ff.firebaseapp.com',
    storageBucket: 'act12-c39ff.firebasestorage.app',
    measurementId: 'G-PCZRTTQXC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU-qzpNIEiRpa9IZTRu8sIPmh8dVYF2Iw',
    appId: '1:465367019073:android:cad6120cbfa4b59d23a0c0',
    messagingSenderId: '465367019073',
    projectId: 'act12-c39ff',
    storageBucket: 'act12-c39ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9xAnOlsugRYTwQLyUwsqpebjHVtKQXbI',
    appId: '1:465367019073:ios:0307dcc1e4443f4723a0c0',
    messagingSenderId: '465367019073',
    projectId: 'act12-c39ff',
    storageBucket: 'act12-c39ff.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9xAnOlsugRYTwQLyUwsqpebjHVtKQXbI',
    appId: '1:465367019073:ios:0307dcc1e4443f4723a0c0',
    messagingSenderId: '465367019073',
    projectId: 'act12-c39ff',
    storageBucket: 'act12-c39ff.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB61lowyAhUQ7QTAIIBV9dStMB08fOfqb0',
    appId: '1:465367019073:web:9ffa37b955a66a1123a0c0',
    messagingSenderId: '465367019073',
    projectId: 'act12-c39ff',
    authDomain: 'act12-c39ff.firebaseapp.com',
    storageBucket: 'act12-c39ff.firebasestorage.app',
    measurementId: 'G-S8VTC4DCV8',
  );
}
